name: ci

on:
  push:
    branches:
      - addKubernates # for testing
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@main
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/intercars-be:$(echo $GITHUB_SHA | head -c7) --target final .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/intercars-be:$(echo $GITHUB_SHA | head -c7)

